# Generated by Django 2.2.5 on 2019-12-02 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=150, unique=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Course')),
            ],
        ),
    ]
