# Generated by Django 2.2.5 on 2019-12-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('hr_name', models.CharField(max_length=200)),
                ('hr_username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('hr_password', models.CharField(max_length=100)),
            ],
        ),
    ]
