# Generated by Django 2.2.5 on 2019-12-02 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('trainer_name', models.CharField(max_length=200)),
                ('trainer_username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('trainer_password', models.CharField(max_length=100)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Course')),
                ('role_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Role')),
            ],
        ),
    ]
