# Generated by Django 2.2.5 on 2019-12-02 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=200)),
                ('user_address', models.CharField(max_length=250)),
                ('user_mobile', models.IntegerField()),
                ('user_doj', models.DateTimeField()),
                ('user_email', models.CharField(max_length=200)),
                ('user_username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=200)),
                ('confirm_password', models.CharField(max_length=200)),
                ('user_payment', models.IntegerField()),
                ('batch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Batch')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Course')),
                ('role_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Role')),
            ],
        ),
    ]
