# Generated by Django 2.2.5 on 2019-12-02 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_data', models.CharField(max_length=250)),
                ('feedback_date', models.DateField()),
                ('feedback_comment', models.CharField(max_length=350, null=True)),
                ('batch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Batch')),
                ('trainer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Trainer')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.User')),
            ],
        ),
    ]
